version: '3'
services:
  mysql:
    image: mysql:8.0.17
    restart: always
    container_name: db-master
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "socialnetwork"
    ports:
      - "3310:3306"
    volumes:
#      - database:/var/lib/mysql:rw
      - ./build_env/mysql/master.cnf:/etc/my.cnf.d/repl.cnf
      - ./build_env/mysql/master.sql:/docker-entrypoint-initdb.d/start.sql
  mysqlread1:
    image: mysql:8.0.17
    container_name: db-slave1
    volumes:
      - ./build_env/mysql/slave1.cnf:/etc/my.cnf.d/repl.cnf
      - ./build_env/mysql/slave.sql:/docker-entrypoint-initdb.d/start.sql
    depends_on:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "socialnetwork"
  mysqlread2:
    image: mysql:8.0.17
    container_name: db-slave2
    volumes:
      - ./build_env/mysql/slave2.cnf:/etc/my.cnf.d/repl.cnf
      - ./build_env/mysql/slave.sql:/docker-entrypoint-initdb.d/start.sql
    depends_on:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "socialnetwork"

  hla:
    build: .
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-db:3306/socialnetwork?useUnicode=true&serverTimezone=UTC"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    ports:
      - "8080:8080"
      - "8000:8000"
  nginx_client:
    build: ./client
    ports:
      -  "8888:8888"
    volumes:
      - ./client/html:/usr/share/nginx/html
    links:
      - hla
    depends_on:
      - hla
volumes:
  database:
